-- Phase 2d: six new step types. Audio uploads (voice notes) reuse MediaAsset; video is linked.
ALTER TYPE "StepType" ADD VALUE IF NOT EXISTS 'COUNTDOWN';
ALTER TYPE "StepType" ADD VALUE IF NOT EXISTS 'PUZZLE';
ALTER TYPE "StepType" ADD VALUE IF NOT EXISTS 'PHOTO_GALLERY';
ALTER TYPE "StepType" ADD VALUE IF NOT EXISTS 'VOICE_NOTE';
ALTER TYPE "StepType" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "StepType" ADD VALUE IF NOT EXISTS 'PLACE_REVEAL';
