/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["IdentityController_createOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["IdentityController_me"];
        put?: never;
        post?: never;
        delete: operations["IdentityController_deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TemplatesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{experienceId}/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{experienceId}/media/{mediaId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{experienceId}/draft/gifts/{stepKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GiftsController_get"];
        put: operations["GiftsController_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExperiencesController_list"];
        put?: never;
        post: operations["ExperiencesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/manage-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExperiencesController_manageLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExperiencesController_detail"];
        put?: never;
        post?: never;
        delete: operations["ExperiencesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExperiencesController_draft"];
        put: operations["ExperiencesController_saveDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExperiencesController_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExperiencesController_enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/expire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExperiencesController_expire"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/expiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ExperiencesController_setExpiry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/publish-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublishingController_check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublishingController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/share-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublishingController_shareLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/share-link/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublishingController_rotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublicController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicController_resume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/session/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublicController_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/session/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublicController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/session/gift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublicController_reveal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/experiences/{token}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PublicController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ResultsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/experiences/{id}/entitlement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_grantEntitlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_reports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reports/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_experiences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/experiences/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/experiences/{id}/takedown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_takedown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/experiences/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_auditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OwnerTokenResponseDto_Output: {
            ownerToken: string;
        };
        MeResponseDto_Output: {
            /** Format: uuid */
            id: string;
            email: string | null;
            displayName: string | null;
            isAdmin: boolean;
        };
        TemplateListResponseDto_Output: {
            items: {
                key: string;
                name: string;
                description: string;
                stepCount: number;
                /** @enum {string} */
                tier: "FREE" | "PLUS" | "PRO";
            }[];
        };
        CreateUploadRequestDto: {
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp" | "image/gif";
            sizeBytes: number;
        };
        CreateUploadResponseDto_Output: {
            /** Format: uuid */
            mediaId: string;
            upload: {
                url: string;
                /** @constant */
                method: "PUT";
                headers: {
                    [key: string]: string;
                };
                /** Format: date-time */
                expiresAt: string;
            };
        };
        MediaAssetDto_Output: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING_UPLOAD" | "READY" | "REJECTED";
            mimeType: string;
            sizeBytes: number | null;
            width: number | null;
            height: number | null;
            url: string | null;
        };
        GiftSecret_Output: {
            /** @constant */
            kind: "VOUCHER_CODE";
            code: string;
            /** @default  */
            pin: string;
            /** @default  */
            redeemUrl: string | "";
            /** @default  */
            instructions: string;
        } | {
            /** @constant */
            kind: "URL";
            /** Format: uri */
            url: string;
            /** @default  */
            instructions: string;
        } | {
            /** @constant */
            kind: "QR_IMAGE";
            /** Format: uuid */
            mediaId: string;
            /** @default  */
            instructions: string;
        } | {
            /** @constant */
            kind: "INSTRUCTION";
            instructions: string;
        } | {
            /** @constant */
            kind: "PHYSICAL_MESSAGE";
            message: string;
        };
        GiftSecretResponseDto_Output: {
            secret: components["schemas"]["GiftSecret_Output"] | null;
        };
        GiftSecret: {
            /** @constant */
            kind: "VOUCHER_CODE";
            code: string;
            /** @default  */
            pin: string;
            /** @default  */
            redeemUrl: string | "";
            /** @default  */
            instructions: string;
        } | {
            /** @constant */
            kind: "URL";
            /** Format: uri */
            url: string;
            /** @default  */
            instructions: string;
        } | {
            /** @constant */
            kind: "QR_IMAGE";
            /** Format: uuid */
            mediaId: string;
            /** @default  */
            instructions: string;
        } | {
            /** @constant */
            kind: "INSTRUCTION";
            instructions: string;
        } | {
            /** @constant */
            kind: "PHYSICAL_MESSAGE";
            message: string;
        };
        GiftSecretRequestDto: {
            secret: components["schemas"]["GiftSecret"];
        };
        ExperienceListResponseDto_Output: {
            items: {
                /** Format: uuid */
                id: string;
                title: string;
                /** @enum {string} */
                status: "DRAFT" | "PUBLISHED" | "DISABLED" | "EXPIRED" | "DELETED";
                /** @enum {string} */
                moderationState: "ACTIVE" | "TAKEN_DOWN";
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                publishedAt: string | null;
                expiresAt: string | null;
                stats: {
                    started: number;
                    completed: number;
                };
            }[];
            nextCursor: string | null;
        };
        CreateExperienceRequestDto: {
            title?: string;
            templateKey?: string | null;
        };
        ExperienceDetailDto_Output: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "DISABLED" | "EXPIRED" | "DELETED";
            /** @enum {string} */
            moderationState: "ACTIVE" | "TAKEN_DOWN";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            publishedAt: string | null;
            expiresAt: string | null;
            stats: {
                started: number;
                completed: number;
            };
            settings: {
                /** @enum {string} */
                responseVisibility: "FULL" | "AGGREGATE_ONLY";
            };
            publishedVersion: number | null;
            hasUnpublishedChanges: boolean;
            takedownReason: string | null;
            tier: {
                /** @enum {string} */
                required: "FREE" | "PLUS" | "PRO";
                /** @enum {string} */
                held: "FREE" | "PLUS" | "PRO";
                satisfied: boolean;
            };
        };
        ManageLinkResponseDto_Output: {
            manageToken: string;
        };
        Theme_Output: {
            palette: {
                background: string;
                surface: string;
                text: string;
                accent: string;
                accentText: string;
            };
            /** @enum {string} */
            font: "SANS" | "SERIF" | "ROUNDED" | "MONO";
            /** @enum {string} */
            typeScale: "COMPACT" | "COMFORTABLE" | "LARGE";
            /** @enum {string} */
            animation: "NONE" | "FADE" | "SLIDE" | "POP";
        };
        Step_Output: {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "MESSAGE";
            config: {
                /** @default  */
                heading: string;
                /**
                 * @default {
                 *       "type": "doc",
                 *       "content": [
                 *         {
                 *           "type": "paragraph"
                 *         }
                 *       ]
                 *     }
                 */
                body: components["schemas"]["RichTextDoc_Output"];
                /** @default Continue */
                buttonLabel: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "IMAGE";
            config: {
                /** @default null */
                mediaId: string | null;
                /** @default  */
                alt: string;
                /** @default  */
                caption: string;
                /** @default Continue */
                buttonLabel: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "MULTIPLE_CHOICE";
            config: {
                /** @default  */
                question: string;
                options: {
                    id: string;
                    label: string;
                }[];
                /** @default null */
                correctOptionId: string | null;
                /** @default false */
                requireCorrect: boolean;
                /** @default Not quite — try again! */
                wrongAnswerMessage: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "YES_NO_CHOICE";
            config: {
                /** @default  */
                question: string;
                /** @default Yes */
                yesLabel: string;
                /** @default No */
                noLabel: string;
                /** @default false */
                maybeEnabled: boolean;
                /** @default Maybe */
                maybeLabel: string;
                /**
                 * @default {
                 *       "mode": "IMMEDIATE"
                 *     }
                 */
                noButton: {
                    /** @constant */
                    mode: "IMMEDIATE";
                } | {
                    /** @constant */
                    mode: "AFTER_ATTEMPTS";
                    attempts: number;
                } | {
                    /** @constant */
                    mode: "AFTER_DELAY";
                    delaySeconds: number;
                } | {
                    /** @constant */
                    mode: "EVASIVE";
                };
                /** @default Nice try! */
                evasiveMessage: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "SCRATCH_REVEAL";
            config: {
                /** @default Scratch to reveal */
                instructions: string;
                /** @default Scratch here */
                coverLabel: string;
                /** @default  */
                hiddenText: string;
                /** @default null */
                hiddenMediaId: string | null;
                /** @default  */
                hiddenMediaAlt: string;
                /** @default Continue */
                buttonLabel: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "GIFT_REVEAL";
            config: {
                /** @default Your surprise */
                title: string;
                /**
                 * @default {
                 *       "type": "doc",
                 *       "content": [
                 *         {
                 *           "type": "paragraph"
                 *         }
                 *       ]
                 *     }
                 */
                message: components["schemas"]["RichTextDoc_Output"];
                /**
                 * @default PHYSICAL_MESSAGE
                 * @enum {string}
                 */
                kind: "VOUCHER_CODE" | "URL" | "QR_IMAGE" | "INSTRUCTION" | "PHYSICAL_MESSAGE";
                /** @default Reveal my surprise */
                revealButtonLabel: string;
                /** @default false */
                oneTimeReveal: boolean;
            };
        };
        RichTextDoc_Output: {
            /** @constant */
            type: "doc";
            content: ({
                /** @constant */
                type: "paragraph";
                content?: ({
                    /** @constant */
                    type: "text";
                    text: string;
                    marks?: {
                        /** @enum {string} */
                        type: "bold" | "italic";
                    }[];
                } | {
                    /** @constant */
                    type: "hardBreak";
                })[];
            } | {
                /** @constant */
                type: "heading";
                attrs: {
                    level: 2 | 3;
                };
                content?: ({
                    /** @constant */
                    type: "text";
                    text: string;
                    marks?: {
                        /** @enum {string} */
                        type: "bold" | "italic";
                    }[];
                } | {
                    /** @constant */
                    type: "hardBreak";
                })[];
            } | {
                /** @constant */
                type: "bulletList";
                content: {
                    /** @constant */
                    type: "listItem";
                    content: {
                        /** @constant */
                        type: "paragraph";
                        content?: ({
                            /** @constant */
                            type: "text";
                            text: string;
                            marks?: {
                                /** @enum {string} */
                                type: "bold" | "italic";
                            }[];
                        } | {
                            /** @constant */
                            type: "hardBreak";
                        })[];
                    }[];
                }[];
            })[];
        };
        DraftDocumentDto_Output: {
            /** Format: uuid */
            experienceId: string;
            revision: number;
            title: string;
            theme: components["schemas"]["Theme_Output"];
            settings: {
                /** @enum {string} */
                responseVisibility: "FULL" | "AGGREGATE_ONLY";
            };
            steps: components["schemas"]["Step_Output"][];
            gifts: {
                /** Format: uuid */
                stepKey: string;
                hasSecret: boolean;
            }[];
            media: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
            }[];
            /** Format: date-time */
            updatedAt: string;
        };
        Theme: {
            palette: {
                background: string;
                surface: string;
                text: string;
                accent: string;
                accentText: string;
            };
            /** @enum {string} */
            font: "SANS" | "SERIF" | "ROUNDED" | "MONO";
            /** @enum {string} */
            typeScale: "COMPACT" | "COMFORTABLE" | "LARGE";
            /** @enum {string} */
            animation: "NONE" | "FADE" | "SLIDE" | "POP";
        };
        Step: {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "MESSAGE";
            config: {
                /** @default  */
                heading: string;
                /**
                 * @default {
                 *       "type": "doc",
                 *       "content": [
                 *         {
                 *           "type": "paragraph"
                 *         }
                 *       ]
                 *     }
                 */
                body: components["schemas"]["RichTextDoc"];
                /** @default Continue */
                buttonLabel: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "IMAGE";
            config: {
                /** @default null */
                mediaId: string | null;
                /** @default  */
                alt: string;
                /** @default  */
                caption: string;
                /** @default Continue */
                buttonLabel: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "MULTIPLE_CHOICE";
            config: {
                /** @default  */
                question: string;
                options: {
                    id: string;
                    label: string;
                }[];
                /** @default null */
                correctOptionId: string | null;
                /** @default false */
                requireCorrect: boolean;
                /** @default Not quite — try again! */
                wrongAnswerMessage: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "YES_NO_CHOICE";
            config: {
                /** @default  */
                question: string;
                /** @default Yes */
                yesLabel: string;
                /** @default No */
                noLabel: string;
                /** @default false */
                maybeEnabled: boolean;
                /** @default Maybe */
                maybeLabel: string;
                /**
                 * @default {
                 *       "mode": "IMMEDIATE"
                 *     }
                 */
                noButton: {
                    /** @constant */
                    mode: "IMMEDIATE";
                } | {
                    /** @constant */
                    mode: "AFTER_ATTEMPTS";
                    attempts: number;
                } | {
                    /** @constant */
                    mode: "AFTER_DELAY";
                    delaySeconds: number;
                } | {
                    /** @constant */
                    mode: "EVASIVE";
                };
                /** @default Nice try! */
                evasiveMessage: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "SCRATCH_REVEAL";
            config: {
                /** @default Scratch to reveal */
                instructions: string;
                /** @default Scratch here */
                coverLabel: string;
                /** @default  */
                hiddenText: string;
                /** @default null */
                hiddenMediaId: string | null;
                /** @default  */
                hiddenMediaAlt: string;
                /** @default Continue */
                buttonLabel: string;
            };
        } | {
            /** Format: uuid */
            key: string;
            /** @constant */
            type: "GIFT_REVEAL";
            config: {
                /** @default Your surprise */
                title: string;
                /**
                 * @default {
                 *       "type": "doc",
                 *       "content": [
                 *         {
                 *           "type": "paragraph"
                 *         }
                 *       ]
                 *     }
                 */
                message: components["schemas"]["RichTextDoc"];
                /**
                 * @default PHYSICAL_MESSAGE
                 * @enum {string}
                 */
                kind: "VOUCHER_CODE" | "URL" | "QR_IMAGE" | "INSTRUCTION" | "PHYSICAL_MESSAGE";
                /** @default Reveal my surprise */
                revealButtonLabel: string;
                /** @default false */
                oneTimeReveal: boolean;
            };
        };
        RichTextDoc: {
            /** @constant */
            type: "doc";
            content: ({
                /** @constant */
                type: "paragraph";
                content?: ({
                    /** @constant */
                    type: "text";
                    text: string;
                    marks?: {
                        /** @enum {string} */
                        type: "bold" | "italic";
                    }[];
                } | {
                    /** @constant */
                    type: "hardBreak";
                })[];
            } | {
                /** @constant */
                type: "heading";
                attrs: {
                    level: 2 | 3;
                };
                content?: ({
                    /** @constant */
                    type: "text";
                    text: string;
                    marks?: {
                        /** @enum {string} */
                        type: "bold" | "italic";
                    }[];
                } | {
                    /** @constant */
                    type: "hardBreak";
                })[];
            } | {
                /** @constant */
                type: "bulletList";
                content: {
                    /** @constant */
                    type: "listItem";
                    content: {
                        /** @constant */
                        type: "paragraph";
                        content?: ({
                            /** @constant */
                            type: "text";
                            text: string;
                            marks?: {
                                /** @enum {string} */
                                type: "bold" | "italic";
                            }[];
                        } | {
                            /** @constant */
                            type: "hardBreak";
                        })[];
                    }[];
                }[];
            })[];
        };
        UpdateDraftRequestDto: {
            revision: number;
            title: string;
            theme: components["schemas"]["Theme"];
            settings: {
                /** @enum {string} */
                responseVisibility: "FULL" | "AGGREGATE_ONLY";
            };
            steps: components["schemas"]["Step"][];
        };
        UpdateDraftResponseDto_Output: {
            revision: number;
            /** Format: date-time */
            updatedAt: string;
        };
        SetExpiryRequestDto: {
            expiresAt: string | null;
        };
        PublishCheckResponseDto_Output: {
            ok: boolean;
            issues: {
                stepKey: string | null;
                field: string | null;
                message: string;
            }[];
        };
        PublishResponseDto_Output: {
            versionNumber: number;
            /** Format: date-time */
            publishedAt: string;
        };
        ShareLinkResponseDto_Output: {
            shareToken: string;
        };
        PublicExperienceMetaDto_Output: {
            title: string;
            theme: components["schemas"]["Theme_Output"];
        };
        SessionStateResponseDto_Output: {
            sessionToken: string;
            experience: {
                title: string;
                theme: components["schemas"]["Theme_Output"];
                versionNumber: number;
                responsesVisibleToCreator: boolean;
                steps: components["schemas"]["Step_Output"][];
                media: {
                    /** Format: uuid */
                    id: string;
                    url: string;
                    width: number | null;
                    height: number | null;
                }[];
            };
            progress: {
                completedStepKeys: string[];
                nextStepKey: string | null;
                completed: boolean;
                giftRevealed: boolean;
            };
        };
        Answer: {
            /** @constant */
            kind: "ACK";
        } | {
            /** @constant */
            kind: "OPTION";
            optionId: string;
        } | {
            /** @constant */
            kind: "CHOICE";
            /** @enum {string} */
            value: "YES" | "NO" | "MAYBE";
        };
        SubmitAnswerRequestDto: {
            /** Format: uuid */
            stepKey: string;
            answer: components["schemas"]["Answer"];
        };
        SubmitAnswerResponseDto_Output: {
            progress: {
                completedStepKeys: string[];
                nextStepKey: string | null;
                completed: boolean;
                giftRevealed: boolean;
            };
            correct: boolean[];
        };
        RevealGiftRequestDto: {
            /** Format: uuid */
            stepKey: string;
        };
        RevealedGift_Output: {
            /** @constant */
            kind: "VOUCHER_CODE";
            code: string;
            pin: string;
            redeemUrl: string;
            instructions: string;
        } | {
            /** @constant */
            kind: "URL";
            url: string;
            instructions: string;
        } | {
            /** @constant */
            kind: "QR_IMAGE";
            imageUrl: string;
            instructions: string;
        } | {
            /** @constant */
            kind: "INSTRUCTION";
            instructions: string;
        } | {
            /** @constant */
            kind: "PHYSICAL_MESSAGE";
            message: string;
        };
        RevealGiftResponseDto_Output: {
            gift: components["schemas"]["RevealedGift_Output"];
            progress: {
                completedStepKeys: string[];
                nextStepKey: string | null;
                completed: boolean;
                giftRevealed: boolean;
            };
        };
        ReportAbuseRequestDto: {
            /** @enum {string} */
            category: "HARASSMENT" | "SEXUAL_CONTENT" | "HATE" | "SCAM_OR_FRAUD" | "VIOLENCE" | "COPYRIGHT" | "OTHER";
            /** @default  */
            details: string;
        };
        AcceptedResponseDto_Output: {
            /** @constant */
            accepted: true;
        };
        Answer_Output: {
            /** @constant */
            kind: "ACK";
        } | {
            /** @constant */
            kind: "OPTION";
            optionId: string;
        } | {
            /** @constant */
            kind: "CHOICE";
            /** @enum {string} */
            value: "YES" | "NO" | "MAYBE";
        };
        ResultsResponseDto_Output: {
            /** @enum {string} */
            responseVisibility: "FULL" | "AGGREGATE_ONLY";
            started: number;
            completed: number;
            closedEarly: number;
            steps: {
                /** Format: uuid */
                stepKey: string;
                type: string;
                label: string;
                tallies: {
                    value: string;
                    label: string;
                    count: number;
                }[];
            }[];
            responses: {
                label: string;
                startedOn: string;
                completed: boolean;
                answers: {
                    /** Format: uuid */
                    stepKey: string;
                    answer: components["schemas"]["Answer_Output"];
                }[];
            }[] | null;
        };
        GrantEntitlementRequestDto: {
            /** @enum {string} */
            tier: "FREE" | "PLUS" | "PRO";
            note?: string;
        };
        AdminReportListResponseDto_Output: {
            items: {
                /** Format: uuid */
                id: string;
                experienceId: string | null;
                experienceTitle: string | null;
                /** @enum {string} */
                category: "HARASSMENT" | "SEXUAL_CONTENT" | "HATE" | "SCAM_OR_FRAUD" | "VIOLENCE" | "COPYRIGHT" | "OTHER";
                details: string;
                /** @enum {string} */
                status: "OPEN" | "ACTIONED" | "DISMISSED";
                resolutionNote: string | null;
                /** Format: date-time */
                createdAt: string;
                resolvedAt: string | null;
            }[];
            nextCursor: string | null;
        };
        ResolveReportRequestDto: {
            /** @enum {string} */
            resolution: "ACTIONED" | "DISMISSED";
            /** @default  */
            note: string;
        };
        AdminExperienceListResponseDto_Output: {
            items: {
                /** Format: uuid */
                id: string;
                title: string;
                /** Format: uuid */
                ownerId: string;
                /** @enum {string} */
                status: "DRAFT" | "PUBLISHED" | "DISABLED" | "EXPIRED" | "DELETED";
                /** @enum {string} */
                moderationState: "ACTIVE" | "TAKEN_DOWN";
                openReports: number;
                /** Format: date-time */
                createdAt: string;
                publishedAt: string | null;
            }[];
            nextCursor: string | null;
        };
        AdminContentDto_Output: {
            title: string;
            theme: components["schemas"]["Theme_Output"];
            versionNumber: number;
            responsesVisibleToCreator: boolean;
            steps: components["schemas"]["Step_Output"][];
            media: {
                /** Format: uuid */
                id: string;
                url: string;
                width: number | null;
                height: number | null;
            }[];
        };
        TakedownRequestDto: {
            reason: string;
        };
        AuditLogListResponseDto_Output: {
            items: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                actorType: "USER" | "ADMIN" | "RECIPIENT" | "SYSTEM";
                actorId: string | null;
                action: string;
                targetType: string;
                targetId: string | null;
                metadata: {
                    [key: string]: string | number | boolean | null;
                };
                requestId: string | null;
                /** Format: date-time */
                createdAt: string;
            }[];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    IdentityController_createOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerTokenResponseDto_Output"];
                };
            };
        };
    };
    IdentityController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto_Output"];
                };
            };
        };
    };
    IdentityController_deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TemplatesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponseDto_Output"];
                };
            };
        };
    };
    MediaController_createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experienceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadResponseDto_Output"];
                };
            };
        };
    };
    MediaController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experienceId: string;
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetDto_Output"];
                };
            };
        };
    };
    GiftsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experienceId: string;
                stepKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftSecretResponseDto_Output"];
                };
            };
        };
    };
    GiftsController_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experienceId: string;
                stepKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GiftSecretRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftSecretResponseDto_Output"];
                };
            };
        };
    };
    ExperiencesController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                status?: "DRAFT" | "PUBLISHED" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceListResponseDto_Output"];
                };
            };
        };
    };
    ExperiencesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExperienceRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceDetailDto_Output"];
                };
            };
        };
    };
    ExperiencesController_manageLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManageLinkResponseDto_Output"];
                };
            };
        };
    };
    ExperiencesController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceDetailDto_Output"];
                };
            };
        };
    };
    ExperiencesController_remove: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retry-safe request key (8-100 chars) */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperiencesController_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDocumentDto_Output"];
                };
            };
        };
    };
    ExperiencesController_saveDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDraftRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateDraftResponseDto_Output"];
                };
            };
        };
    };
    ExperiencesController_disable: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retry-safe request key (8-100 chars) */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperiencesController_enable: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retry-safe request key (8-100 chars) */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperiencesController_expire: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retry-safe request key (8-100 chars) */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExperiencesController_setExpiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetExpiryRequestDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublishingController_check: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishCheckResponseDto_Output"];
                };
            };
        };
    };
    PublishingController_publish: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retry-safe request key (8-100 chars) */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponseDto_Output"];
                };
            };
        };
    };
    PublishingController_shareLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkResponseDto_Output"];
                };
            };
        };
    };
    PublishingController_rotate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkResponseDto_Output"];
                };
            };
        };
    };
    PublicController_meta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicExperienceMetaDto_Output"];
                };
            };
        };
    };
    PublicController_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponseDto_Output"];
                };
            };
        };
    };
    PublicController_resume: {
        parameters: {
            query?: never;
            header: {
                /** @description Recipient session token */
                "x-recipient-session": string;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponseDto_Output"];
                };
            };
        };
    };
    PublicController_answer: {
        parameters: {
            query?: never;
            header: {
                /** @description Recipient session token */
                "x-recipient-session": string;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAnswerResponseDto_Output"];
                };
            };
        };
    };
    PublicController_close: {
        parameters: {
            query?: never;
            header: {
                /** @description Recipient session token */
                "x-recipient-session": string;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_reveal: {
        parameters: {
            query?: never;
            header: {
                /** @description Recipient session token */
                "x-recipient-session": string;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealGiftRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevealGiftResponseDto_Output"];
                };
            };
        };
    };
    PublicController_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportAbuseRequestDto"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedResponseDto_Output"];
                };
            };
        };
    };
    ResultsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsResponseDto_Output"];
                };
            };
        };
    };
    AdminController_grantEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantEntitlementRequestDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_reports: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReportListResponseDto_Output"];
                };
            };
        };
    };
    AdminController_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveReportRequestDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_experiences: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminExperienceListResponseDto_Output"];
                };
            };
        };
    };
    AdminController_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContentDto_Output"];
                };
            };
        };
    };
    AdminController_takedown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakedownRequestDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_auditLogs: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponseDto_Output"];
                };
            };
        };
    };
}
